### ISSUE TITLE
The error on python package installation of gpmp2

### ISSUE THREAD

**Issue by WangHonghui123** [borglab/gpmp2#12]
Hi, I am currently installing python package installation of gpmp2 after I have installed GTSAM and its python wrapper.

When I use command "cmake -DGPMP2_BUILD_PYTHON_TOOLBOX:=ON .."  The error happens, shown as follows:

-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include
-- Building Module: geometry
-- Building Module: gp
-- Building Module: kinematics
-- Building Module: dynamics
-- Building Module: obstacle
-- Building Module: planner
-- Building Module: utils
-- GPMP2 Version: 0.3.0
-- Install prefix: /usr/local
-- Build shared library
CMake Warning at python/CMakeLists.txt:1 (find_package):
  By not providing "Findgtwrap.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gtwrap", but
  CMake did not find one.

  Could not find a package configuration file provided by "gtwrap" with any
  of the following names:

    gtwrapConfig.cmake
    gtwrap-config.cmake

  Add the installation prefix of "gtwrap" to CMAKE_PREFIX_PATH or set
  "gtwrap_DIR" to a directory containing one of the above files.  If "gtwrap"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Error at python/CMakeLists.txt:7 (gtwrap_get_python_version):
  Unknown CMake command "gtwrap_get_python_version".

-- Configuring incomplete, errors occurred!
See also "/home/test/PycharmProjects/pythonProject/gpmp2/build/CMakeFiles/CMakeOutput.log".
See also "/home/test/PycharmProjects/pythonProject/gpmp2/build/CMakeFiles/CMakeError.log".

I would like to know how to fix it. Thanks.

**Comment by varunvupparige** [comment]
I'm facing the same issue. Any fixes?

**Comment by varunagrawal** [comment]
Have you installed GTSAM with the Python wrapper installed? That will install the gtwrap package which is used for generating the Python bindings.

**Comment by mattking-smith** [comment]
> Have you installed GTSAM with the Python wrapper installed? That will install the gtwrap package which is used for generating the Python bindings.

@varunagrawal I am looking the instruction at the [ReadMe.md](https://github.com/borglab/gpmp2/blob/master/README.md) and we do not make a comment about needing to have `GTSAM` with the Python wrapper installed... Do we need to update this?

**Comment by varunvupparige** [comment]
@varunagrawal @mattking-smith After installing the GTSAM with python wrapper, when I try to install the gpmp2 according the readme file, I run into the following error:


Traceback (most recent call last):
  File "/usr/local/bin/gtwrap/pybind_wrap.py", line 94, in <module>
    main()
  File "/usr/local/bin/gtwrap/pybind_wrap.py", line 90, in main
    wrapper.wrap(sources, args.out)
  File "/usr/local/lib/gtwrap/gtwrap/pybind_wrapper.py", line 718, in wrap
    submodules=submodules)
  File "/usr/local/lib/gtwrap/gtwrap/pybind_wrapper.py", line 669, in wrap_file
    submodules_init="\n".join(submodules_init),
KeyError: 'include_boost'
python/CMakeFiles/pybind_wrap_gpmp2.dir/build.make:75: recipe for target 'python/gpmp2.cpp' failed
make[3]: *** [python/gpmp2.cpp] Error 1
CMakeFiles/Makefile2:2677: recipe for target 'python/CMakeFiles/pybind_wrap_gpmp2.dir/all' failed
make[2]: *** [python/CMakeFiles/pybind_wrap_gpmp2.dir/all] Error 2
CMakeFiles/Makefile2:2737: recipe for target 'python/CMakeFiles/python-install.dir/rule' failed
make[1]: *** [python/CMakeFiles/python-install.dir/rule] Error 2
Makefile:1323: recipe for target 'python-install' failed
make: *** [python-install] Error 2

**Comment by varunagrawal** [comment]
@varunvupparige #13 will resolve that issue. Matt has been a bit busy but we'll hopefully land that PR soon.

In the meantime, I recommend checking out that branch and using it instead of master.

**Comment by varunvupparige** [comment]
@varunagrawal I run into a different error when I build (make -j8) the `upgrade` branch instead `master`. 
Would you recommend using this repo instead: https://github.com/gtrll/gpmp2?
What are the major additions to gpmp2 between these two repos?



Here is the error output for your reference:

[ 42%] Building CXX object gpmp2/CMakeFiles/gpmp2.dir/kinematics/Pose2MobileVetLinArm.cpp.o
gpmp2/CMakeFiles/gpmp2.dir/build.make:103: recipe for target 'gpmp2/CMakeFiles/gpmp2.dir/kinematics/PointRobot.cpp.o' failed
make[2]: *** [gpmp2/CMakeFiles/gpmp2.dir/kinematics/PointRobot.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
gpmp2/CMakeFiles/gpmp2.dir/build.make:145: recipe for target 'gpmp2/CMakeFiles/gpmp2.dir/kinematics/Pose2MobileBase.cpp.o' failed
make[2]: *** [gpmp2/CMakeFiles/gpmp2.dir/kinematics/Pose2MobileBase.cpp.o] Error 1
gpmp2/CMakeFiles/gpmp2.dir/build.make:89: recipe for target 'gpmp2/CMakeFiles/gpmp2.dir/kinematics/Arm.cpp.o' failed
make[2]: *** [gpmp2/CMakeFiles/gpmp2.dir/kinematics/Arm.cpp.o] Error 1
gpmp2/CMakeFiles/gpmp2.dir/build.make:131: recipe for target 'gpmp2/CMakeFiles/gpmp2.dir/kinematics/Pose2MobileArm.cpp.o' failed
make[2]: *** [gpmp2/CMakeFiles/gpmp2.dir/kinematics/Pose2MobileArm.cpp.o] Error 1
gpmp2/CMakeFiles/gpmp2.dir/build.make:117: recipe for target 'gpmp2/CMakeFiles/gpmp2.dir/kinematics/Pose2Mobile2Arms.cpp.o' failed
make[2]: *** [gpmp2/CMakeFiles/gpmp2.dir/kinematics/Pose2Mobile2Arms.cpp.o] Error 1
gpmp2/CMakeFiles/gpmp2.dir/build.make:159: recipe for target 'gpmp2/CMakeFiles/gpmp2.dir/kinematics/Pose2MobileVetLin2Arms.cpp.o' failed
make[2]: *** [gpmp2/CMakeFiles/gpmp2.dir/kinematics/Pose2MobileVetLin2Arms.cpp.o] Error 1
[ 42%] Built target pybind_wrap_gpmp2
In file included from /home/varun/gpmp2/gpmp2/geometry/Pose2Vector.h:13:0,
                 from /home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.h:11,
                 from /home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:8:
/home/varun/gpmp2/gpmp2/geometry/ProductDynamicLieGroup.h:23:24: error: expected identifier before ‘(’ token
   GTSAM_CONCEPT_ASSERT((gtsam::IsLieGroup<G>));
                        ^
/home/varun/gpmp2/gpmp2/geometry/ProductDynamicLieGroup.h:23:46: error: ISO C++ forbids declaration of ‘GTSAM_CONCEPT_ASSERT’ with no type [-fpermissive]
   GTSAM_CONCEPT_ASSERT((gtsam::IsLieGroup<G>));
                                              ^
/home/varun/gpmp2/gpmp2/geometry/ProductDynamicLieGroup.h:24:24: error: expected identifier before ‘(’ token
   GTSAM_CONCEPT_ASSERT((gtsam::IsLieGroup<H>));
                        ^
/home/varun/gpmp2/gpmp2/geometry/ProductDynamicLieGroup.h:24:46: error: ISO C++ forbids declaration of ‘GTSAM_CONCEPT_ASSERT’ with no type [-fpermissive]
   GTSAM_CONCEPT_ASSERT((gtsam::IsLieGroup<H>));
                                              ^
In file included from /usr/local/include/gtsam/nonlinear/Values.h:37:0,
                 from /usr/local/include/gtsam/nonlinear/NonlinearFactor.h:23,
                 from /home/varun/gpmp2/gpmp2/kinematics/ForwardKinematics.h:13,
                 from /home/varun/gpmp2/gpmp2/kinematics/Arm.h:12,
                 from /home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.h:12,
                 from /home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:8:
/usr/include/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
In file included from /home/varun/gpmp2/gpmp2/kinematics/Arm.h:12:0,
                 from /home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.h:12,
                 from /home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:8:
/home/varun/gpmp2/gpmp2/kinematics/ForwardKinematics.h:58:28: error: ‘std::optional’ has not been declared
       const Pose& jp, std::optional<const Velocity> jv,
                            ^~~~~~~~
/home/varun/gpmp2/gpmp2/kinematics/ForwardKinematics.h:58:36: error: expected ‘,’ or ‘...’ before ‘<’ token
       const Pose& jp, std::optional<const Velocity> jv,
                                    ^
In file included from /home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.h:12:0,
                 from /home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:8:
/home/varun/gpmp2/gpmp2/kinematics/Arm.h:77:31: error: ‘std::optional’ has not been declared
                          std::optional<const gtsam::Vector> jv,
                               ^~~~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Arm.h:77:39: error: expected ‘,’ or ‘...’ before ‘<’ token
                          std::optional<const gtsam::Vector> jv,
                                       ^
In file included from /home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:8:0:
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.h:65:31: error: ‘std::optional’ has not been declared
                          std::optional<const gtsam::Vector> v,
                               ^~~~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.h:65:39: error: expected ‘,’ or ‘...’ before ‘<’ token
                          std::optional<const gtsam::Vector> v,
                                       ^
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp: In constructor ‘gpmp2::Pose2MobileVetLinArm::Pose2MobileVetLinArm(const gpmp2::Arm&, const gtsam::Pose3&, const gtsam::Pose3&, bool)’:
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:29:39: error: ‘Identity’ is not a member of ‘gtsam::Pose3’
   if (!arm_.base_pose().equals(Pose3::Identity(), 1e-6))
                                       ^~~~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp: At global scope:
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:38:32: error: ‘std::optional’ has not been declared
     const Pose2Vector& p, std::optional<const gtsam::Vector> v,
                                ^~~~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:38:40: error: expected ‘,’ or ‘...’ before ‘<’ token
     const Pose2Vector& p, std::optional<const gtsam::Vector> v,
                                        ^
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp: In member function ‘virtual void gpmp2::Pose2MobileVetLinArm::forwardKinematics(const gpmp2::Pose2Vector&, int) const’:
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:43:7: error: ‘v’ was not declared in this scope
   if (v) throw runtime_error("[Pose2MobileArm] TODO: velocity not implemented");
       ^
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:45:8: error: ‘v’ was not declared in this scope
   if (!v && (vx || J_vx_p || J_vx_v))
        ^
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:45:14: error: ‘vx’ was not declared in this scope
   if (!v && (vx || J_vx_p || J_vx_v))
              ^~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:45:20: error: ‘J_vx_p’ was not declared in this scope
   if (!v && (vx || J_vx_p || J_vx_v))
                    ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:45:20: note: suggested alternative: ‘__exp’
   if (!v && (vx || J_vx_p || J_vx_v))
                    ^~~~~~
                    __exp
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:45:30: error: ‘J_vx_v’ was not declared in this scope
   if (!v && (vx || J_vx_p || J_vx_v))
                              ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:52:3: error: ‘px’ was not declared in this scope
   px.resize(nr_links());
   ^~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:52:3: note: suggested alternative: ‘p’
   px.resize(nr_links());
   ^~
   p
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:53:7: error: ‘vx’ was not declared in this scope
   if (vx) vx->resize(nr_links());
       ^~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:54:7: error: ‘J_px_p’ was not declared in this scope
   if (J_px_p) J_px_p->assign(nr_links(), Matrix::Zero(6, dof()));
       ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:54:7: note: suggested alternative: ‘s_sph_p’
   if (J_px_p) J_px_p->assign(nr_links(), Matrix::Zero(6, dof()));
       ^~~~~~
       s_sph_p
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:55:7: error: ‘J_vx_p’ was not declared in this scope
   if (J_vx_p) J_vx_p->assign(nr_links(), Matrix::Zero(3, dof()));
       ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:55:7: note: suggested alternative: ‘__exp’
   if (J_vx_p) J_vx_p->assign(nr_links(), Matrix::Zero(3, dof()));
       ^~~~~~
       __exp
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:56:7: error: ‘J_vx_v’ was not declared in this scope
   if (J_vx_v) J_vx_v->assign(nr_links(), Matrix::Zero(3, dof()));
       ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:62:7: error: ‘J_px_p’ was not declared in this scope
   if (J_px_p || J_vx_p || J_vx_v) {
       ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:62:7: note: suggested alternative: ‘s_sph_p’
   if (J_px_p || J_vx_p || J_vx_v) {
       ^~~~~~
       s_sph_p
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:62:17: error: ‘J_vx_p’ was not declared in this scope
   if (J_px_p || J_vx_p || J_vx_v) {
                 ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:62:17: note: suggested alternative: ‘__exp’
   if (J_px_p || J_vx_p || J_vx_v) {
                 ^~~~~~
                 __exp
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:62:27: error: ‘J_vx_v’ was not declared in this scope
   if (J_px_p || J_vx_p || J_vx_v) {
                           ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:79:7: error: ‘J_px_p’ was not declared in this scope
   if (J_px_p) (*J_px_p)[0].block<6, 3>(0, 0) = Hveh_base;
       ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:79:7: note: suggested alternative: ‘s_sph_p’
   if (J_px_p) (*J_px_p)[0].block<6, 3>(0, 0) = Hveh_base;
       ^~~~~~
       s_sph_p
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:79:48: error: lvalue required as left operand of assignment
   if (J_px_p) (*J_px_p)[0].block<6, 3>(0, 0) = Hveh_base;
                                                ^~~~~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:83:7: error: ‘J_px_p’ was not declared in this scope
   if (J_px_p) (*J_px_p)[1].block<6, 4>(0, 0) = Htso_base;
       ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:83:7: note: suggested alternative: ‘s_sph_p’
   if (J_px_p) (*J_px_p)[1].block<6, 4>(0, 0) = Htso_base;
       ^~~~~~
       s_sph_p
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:83:48: error: lvalue required as left operand of assignment
   if (J_px_p) (*J_px_p)[1].block<6, 4>(0, 0) = Htso_base;
                                                ^~~~~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:91:26: error: ‘J_px_p’ was not declared in this scope
                          J_px_p ? &Jarm_jpx_jp : nullptr);
                          ^~~~~~
/home/varun/gpmp2/gpmp2/kinematics/Pose2MobileVetLinArm.cpp:91:26: note: suggested alternative: ‘s_sph_p’
                          J_px_p ? &Jarm_jpx_jp : nullptr);

**Comment by mattking-smith** [comment]
@varunvupparige We have merged #13 so make sure you are on the latest `develop` branch of `GTSAM` and then try this compilation again.
